library(tidyverse)
library(vroom)
lan<-vroom("mayanHaynie_GWAS_allAccessions.csv") 
lan_small<-select(lan,"GWAS ID", "Polygon Language Name")
colnames(lan_small)<-c("gwasid","language")
languages<-levels(factor(lan_small$language))
new_dat<-data.frame(sapply(languages, function(i) as.numeric(lan_small$language==i)))
new_new_dat<-cbind(lan_small,new_dat)
write.table(new_new_dat,file="/home/smambakk/language/Maya/0_1_mayan”,row.names=T,quote=F,col.names=T,sep="\t")
dev.off()
